DROP TABLE Plugins
CREATE TABLE Plugins
(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL UNIQUE,
)

DROP TABLE Translations
CREATE TABLE Translations
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	DEU VARCHAR(450),
	USA VARCHAR(450),
	UNIQUE(DEU, USA),
)

DROP TABLE RefBoxViews
CREATE TABLE RefBoxViews
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50) UNIQUE,
	ViewName VARCHAR(50) UNIQUE,
)

DROP TABLE Countries
CREATE TABLE Countries
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Alpha2 VARCHAR(2),
	Alpha3 VARCHAR(3),
	Name VARCHAR(250),
	AreaCode VARCHAR(5),
)

DROP TABLE Addresses
CREATE TABLE Addresses
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Country INT,
	Zip VARCHAR(7),
	City VARCHAR(75),
	Street VARCHAR(100),
	HsNo VARCHAR(10),
	FOREIGN KEY (Country) REFERENCES Countries(ID),
)

DROP TABLE People
CREATE TABLE People
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Code VARCHAR(16),
	Name VARCHAR(250),
	Forename VARCHAR(250),
	Pwd VARCHAR(250) NOT NULL,
	Language INT,
	Address INT,
	FOREIGN KEY (Language) REFERENCES Languages(ID),
	FOREIGN KEY (Address) REFERENCES Addresses(ID),
)

DROP TABLE ContactTypes
CREATE TABLE ContactTypes
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(250),
	Code VARCHAR(16),
	Regex VARCHAR(250),
)

DROP TABLE ContactInformation
CREATE TABLE ContactInformation
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ContactType INT NOT NULL,
	Information VARCHAR(250) NOT NULL,
	FOREIGN KEY (ContactType) REFERENCES ContactTypes(ID),
	UNIQUE (ContactType, Information),
)

DROP TABLE Languages
CREATE TABLE Languages
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(250) NOT NULL UNIQUE,
	Code VARCHAR(3) NOT NULL UNIQUE,
)